replicaCount: 3

env:
  API_ENVIRONMENT: "production"
  LOG_FORMAT: "json"
  LOG_LEVEL: "INFO"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

chroma:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 20Gi

secrets:
  create: false
  existingSecret: "ai-devops-assistant-prod"
